version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_DB_HOST=postgres
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=tik_tak_toe
      - DJANGO_DB_USER=nikakoy-png
      - DJANGO_DB_PASSWORD=root
      - REDIS_HOST=redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tik_tak_toe
      POSTGRES_USER: nikakoy-png
      POSTGRES_PASSWORD: root

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  angular:
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "4200:4200"
    volumes:
      - .:/app
