version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tik_tak_toe
      POSTGRES_USER: nikakoy
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:"

  django:
    build:
      context: ./tik_tak_toe_back
      dockerfile: Dockerfile.django
    depends_on:
      - db
      - redis
    volumes:
      - ./tik_tak_toe_back:/app
    environment:
      - DATABASE_HOST=db
    ports:
      - "8000:8000"

  angular:
    build:
      context: ./tik_tak_toe_front
      dockerfile: Dockerfile.angular
    ports:
      - "4200:443"
