# Generated by Django 4.2.4 on 2023-08-15 12:33

import django.contrib.postgres.fields
from django.db import migrations, models
import play.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play19x19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_hash_code', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=19), blank=True, default=play.models.default_board_19x19, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Play3x3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_hash_code', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=3), blank=True, default=play.models.default_board_3x3, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
