# Generated by Django 4.2.4 on 2023-08-15 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('play', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='play3x3',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays_as_user1_3X3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='play3x3',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays_as_user2_3X3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='play19x19',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays_as_user1_19X19', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='play19x19',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays_as_user2_19X19', to=settings.AUTH_USER_MODEL),
        ),
    ]
