FROM python:3.11

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/

RUN pip install -r requirements.txt

COPY . /app/

RUN python manage.py makemigrations
RUN python manage.py migrate

EXPOSE 8000

CMD ["uvicorn", "tik_tak_toe_back.asgi:application", "--host", "0.0.0.0", "--port", "8000", "--ssl-keyfile", "./ssl/localhost.key", "--ssl-certfile", "./ssl/localhost.crt", "--reload"]
